### ISSUE TITLE
Docker compose : kafka and crawler containers restarting forever

### ISSUE THREAD

**Issue by llermaly** [istresearch/scrapy-cluster#206]
Hello,  I'm trying to make quickstart work but after pulling containers wurstmeister/kafka and scrapy-cluster:crawler containers keep status restarting.

From error logs : 

kafka:
```
 ERROR: No listener or advertised hostname configuration provided in environment.
2018-11-19T22:46:22.884011669Z        Please define KAFKA_LISTENERS / (deprecated) KAFKA_ADVERTISED_HOST_NAME
```

crawler:
```
ERROR: Unable to connect to Kafka in Pipeline, raising exit flag.
2018-11-19T22:47:41.710214263Z Unhandled error in Deferred:
```
Testing pass OK on the other containers but after passing start throwing kafka related errors.

Thanks

**Comment by llermaly** [comment]
Solved :) 

Step 1 : 

Modify docker-compose.yml file inside scrapy-cluster folder, add some enviroment variables : 

```
environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
```
KAFKA_ADVERTISED_HOST_NAME and KAFKA_ADVERTISED_PORT were missing

run docker-compose up --force-recreate -d

now tests are passing
